In [2]:
import numpy as np
#1
list1 = [1,2,4,5,7,8]
array1 = np.array(list1)
print(array1)

[1 2 4 5 7 8]


In [28]:
#2
array2 = np.linspace(7,14,16)
print(array2,"\n\n")
array2 = array2.reshape(4,4)
print(array2)
#array2 = array2.shape(4,4)
#print(array2)

[ 7.          7.46666667  7.93333333  8.4         8.86666667  9.33333333
  9.8        10.26666667 10.73333333 11.2        11.66666667 12.13333333
 12.6        13.06666667 13.53333333 14.        ] 


[[ 7.          7.46666667  7.93333333  8.4       ]
 [ 8.86666667  9.33333333  9.8        10.26666667]
 [10.73333333 11.2        11.66666667 12.13333333]
 [12.6        13.06666667 13.53333333 14.        ]]


In [37]:
#7
array7 = np.append(array1,[11,22])
print(array7)

[ 1  2  4  5  7  8 11 22]


In [40]:
#4
array4 = np.flip(array1)
print(array4)

[8 7 5 4 2 1]
